const fs = require('fs');

const mapsText = fs.readFileSync('maps_generated.json', 'utf8');
const maps = JSON.parse(mapsText);

const teMap = {
    'Dashboard': 'డాష్‌బోర్డ్', 'Overview': 'అవలోకనం', 'Technology': 'సాంకేతికత',
    'Map Tool': 'మ్యాప్ టూల్', 'Predict Yield': 'దిగుబడి అంచనా', 'Impact': 'ప్రభావం',
    'Settings': 'సెట్టింగ్స్', 'Soil Analysis': 'మట్టి విశ్లేషణ',
    'Growth Monitor': 'వృద్ధి పర్యవేక్షణ', 'Carbon Tracking': 'కార్బన్ ట్రాకింగ్',
    'Feedback': 'అభిప్రాయం',
    'OVERVIEW': 'అవలోకనం', 'TECHNOLOGY': 'సాంకేతికత', 'MAP TOOL': 'మ్యాప్ టూల్',
    'YIELD PREDICTOR': 'దిగుబడి అంచనా', 'GLOBAL IMPACT': 'గ్లోబల్ ప్రభావం',
    'AI-Powered Predictions': 'AI-శక్తితో కూడిన అంచనాలు',
    'Global Coverage': 'గ్లోబల్ కవరేజ్', 'Real-time Analytics': 'రియల్-టైమ్ అనలిటిక్స్',
    'Expert Recommendations': 'నిపుణుల సిఫార్సులు', 'Historical Analysis': 'చారిత్రక విశ్లేషణ',
    'Mobile Friendly': 'మొబైల్ ఫ్రెండ్లీ',
    'Prediction Accuracy': 'అంచనా ఖచ్చితత్వం', 'Farmers Served': 'రైతులకు సేవ',
    'Countries Covered': 'కవర్ చేసిన దేశాలు', 'Support Available': 'మద్దతు అందుబాటులో',
    'Cutting-Edge AI Technology': 'అత్యాధునిక AI టెక్నాలజీ',
    'Machine Learning': 'మెషిన్ లెర్నింగ్', 'Satellite Imagery': 'సాటిలైట్ ఇమేజరీ',
    'Weather Analytics': 'వాతావరణ అనలిటిక్స్', 'Soil Analysis': 'మట్టి విశ్లేషణ',
    'Big Data Processing': 'బిగ్ డేటా ప్రాసెసింగ్', 'IoT Integration': 'IoT ఇంటిగ్రేషన్',
    'Our Technology Stack': 'మా టెక్నాలజీ స్టాక్',
    'Environmental Sustainability': 'పర్యావరణ స్థిరత్వం',
    'Economic Growth': 'ఆర్థిక వృద్ధి', 'Food Security': 'ఆహార భద్రత',
    'Digital Inclusion': 'డిజిటల్ చేర్పు', 'Knowledge Transfer': 'జ్ఞాన బదిలీ',
    'Community Impact': 'సమాజ ప్రభావం', 'Success Stories': 'విజయ గాథలు',
    'Real farmers, real results from around the world': 'ప్రపంచవ్యాప్తంగా నిజమైన రైతులు, నిజమైన ఫలితాలు',
    'Language & Region': 'భాష మరియు ప్రాంతం', 'Language': 'భాష', 'Units': 'యూనిట్లు',
    'Notifications': 'నోటిఫికేషన్లు', 'Prediction Updates': 'అంచనా నవీకరణలు',
    'Get notified when new predictions are available': 'కొత్త అంచనాలు అందుబాటులో ఉన్నప్పుడు తెలియజేయండి',
    'Weather Alerts': 'వాతావరణ హెచ్చరికలు',
    'Receive alerts for severe weather conditions': 'తీవ్రమైన వాతావరణ పరిస్థితులకు హెచ్చరికలు అందుకోండి',
    'System Updates': 'సిస్టమ్ నవీకరణలు',
    'Get notified about system maintenance and updates': 'సిస్టమ్ నిర్వహణ మరియు నవీకరణల గురించి తెలియజేయండి',
    'Privacy & Data': 'గోప్యత మరియు డేటా',
    'Analytics & Usage Data': 'అనలిటిక్స్ మరియు వినియోగ డేటా',
    'Help improve our service by sharing anonymous usage data': 'అనామక వినియోగ డేటాను పంచుకోవడం ద్వారా మా సేవను మెరుగుపరచడంలో సహాయం చేయండి',
    'Data Sharing': 'డేటా భాగస్వామ్యం',
    'Share anonymized data with agricultural research institutions': 'వ్యవసాయ పరిశోధన సంస్థలతో అనామకీకరించిన డేటాను పంచుకోండి',
    'Performance': 'పనితీరు', 'Animation Level': 'యానిమేషన్ స్థాయి',
    'No Animations': 'యానిమేషన్లు లేవు', 'Reduced Animations': 'తగ్గించిన యానిమేషన్లు',
    'Normal Animations': 'సాధారణ యానిమేషన్లు', 'Enhanced Animations': 'మెరుగైన యానిమేషన్లు',
    'Account & Data': 'ఖాతా ಮತ್ತು డేటా', 'Export Data': 'డేటా ఎగుమతి',
    'Import Data': 'డేటా దిగుమతి', 'Need Help?': 'సహాయం కావాలా?',
    '24/7 Help Line': '24/7 సహాయ లైన్',
    'Call for immediate assistance': 'తక్షణ సహాయం కోసం కాల్ చేయండి',
    'India:': 'భారతదేశం:', 'International:': 'అంతర్జాతీయ:', 'WhatsApp:': 'వాట్సాప్:',
    'Available 24/7 • Multilingual Support': '24/7 అందుబాటులో • బహుభాషా మద్దతు',
    'Send Feedback': 'అభిప్రాయం పంపండి',
    'Report issues or suggestions': 'సమస్యలు లేదా సూచనలు నివేదించండి',
    'Metric (kg, hectares)': 'మెట్రిక్ (కిలో, హెక్టార్లు)',
    'Imperial (lbs, acres)': 'ఇంపీరియల్ (పౌండ్లు, ఎకరాలు)',
    'Crop Type': 'పంట రకం', 'Location': 'స్థానం', 'Field Size (acres)': 'పొలం పరిమాణం (ఎకరాలు)',
    'Planting Date': 'విత్తన తేదీ', 'Soil Type': 'మట్టి రకం',
    'Irrigation System': 'నీటిపారుదల వ్యవస్థ', 'Fertilizer Usage': 'ఎరువుల వాడకం',
    'Previous Year Yield (tons/acre)': 'గత సంవత్సర దిగుబడి (టన్నులు/ఎకరం)',
    'Additional Notes & Comments': 'అదనపు గమనికలు మరియు వ్యాఖ్యలు',
    'Generate Prediction': 'అంచనా రూపొందించండి',
    'Select Crop Type': 'పంట రకాన్ని ఎంచుకోండి',
    'Select Soil Type': 'మట్టి రకాన్ని ఎంచుకోండి',
    'Select Irrigation Type': 'నీటిపారుదల రకాన్ని ఎంచుకోండి',
    'Select Fertilizer Level': 'ఎరువుల స్థాయిని ఎంచుకోండి',
    'Upload Soil Sample Photo': 'మట్టి నమూనా ఫోటో అప్‌లోడ్ చేయండి',
    'Drop your soil photo here': 'మీ మట్టి ఫోటోను ఇక్కడ వదలండి',
    'or click to browse files': 'లేదా ఫైళ్లను బ్రౌజ్ చేయడానికి క్లిక్ చేయండి',
    'Choose File': 'ఫైల్ ఎంచుకోండి',
    'Photography Tips for Best Results': 'ఉత్తమ ఫలితాల కోసం ఫోటోగ్రఫీ చిట్కాలు',
    'Sandy Soil': 'ఇసుక మట్టి', 'Loamy Soil': 'లోమీ మట్టి', 'Clay Soil': 'బంకమట్టి',
    'Primary Soil Type Detected': 'ప్రాథమిక మట్టి రకం గుర్తించబడింది',
    'Recommended Crops for Your Soil': 'మీ మట్టికి సిఫార్సు చేయబడిన పంటలు',
    'Soil Improvement Tips': 'మట్టి మెరుగుదల చిట్కాలు',
    'Analyzing Soil Texture...': 'మట్టి ఆకృతిని విశ్లేషిస్తోంది...',
    'Add New Crop to Monitor': 'పర్యవేక్షించడానికి కొత్త పంటను జోడించండి',
    'Crop Name': 'పంట పేరు', 'Variety': 'రకం', 'Field Location': 'పొలం స్థానం',
    'Start Monitoring Crop': 'పంట పర్యవేక్షణ ప్రారంభించండి',
    'No Crops Being Monitored': 'పర్యవేక్షించబడుతున్న పంటలు లేవు',
    'Crop Details': 'పంట వివరాలు',
    'Carbon Sequestered': 'కార్బన్ సీక్వెస్టర్డ్',
    'Available Credits': 'అందుబాటులో ఉన్న క్రెడిట్‌లు',
    'Estimated Value': 'అంచనా విలువ', 'Sell Credits': 'క్రెడిట్‌లను అమ్మండి',
    'Calculate Carbon Sequestration': 'కార్బన్ సీక్వెస్ట్రేషన్‌ను లెక్కించండి',
    'Farm Size (acres)': 'వ్యవసాయ పరిమాణం (ఎకరాలు)',
    'Primary Crop Type': 'ప్రాథమిక పంట రకం', 'Farming Method': 'వ్యవసాయ పద్ధతి',
    'Calculate Carbon Impact': 'కార్బన్ ప్రభావాన్ని లెక్కించండి',
    'Carbon Impact Analysis': 'కార్బన్ ప్రభావ విశ్లేషణ',
    'Carbon Credits Marketplace': 'కార్బన్ క్రెడిట్‌ల మార్కెట్‌ప్లేస్',
    'Request Verification': 'ధృవీకరణ అభ్యర్థించండి',
    'List Credits for Sale': 'అమ్మకానికి క్రెడిట్‌లను జాబితా చేయండి',
    'General Feedback': 'సాధారణ అభిప్రాయం', 'Report a Bug': 'బగ్ నివేదించండి',
    'Get Support': 'మద్దతు పొందండి', 'Your Name': 'మీ పేరు',
    'Email Address': 'ఇమెయిల్ చిరునామా', 'Category': 'వర్గం',
    'Your Feedback': 'మీ అభిప్రాయం', 'Submit Feedback': 'అభిప్రాయం సమర్పించండి',
    'Bug Title': 'బగ్ శీర్షిక', 'Priority Level': 'ప్రాధాన్యత స్థాయి',
    'Page/Feature Affected': 'ప్రభావిత పేజీ/ఫీచర్',
    'Detailed Description': 'వివరణాత్మక వివరణ', 'Report Bug': 'బగ్ నివేదించండి',
    'Subject': 'విషయం', 'Detailed Message': 'వివరణాత్మక సందేశం',
    'Submit Support Request': 'మద్దతు అభ్యర్థన సమర్పించండి',
    'Clear Form': 'ఫారమ్ క్లియర్ చేయండి',
    'Email Support': 'ఇమెయిల్ మద్దతు', 'Live Chat': 'లైవ్ చాట్',
    'Documentation': 'డాక్యుమెంటేషన్', 'Get help via email': 'ఇమెయిల్ ద్వారా సహాయం పొందండి',
    'Chat with our team': 'మా బృందంతో చాట్ చేయండి',
    'Browse our help docs': 'మా సహాయ డాక్స్ బ్రౌజ్ చేయండి',
    'Start Chat': 'చాట్ ప్రారంభించండి', 'View Docs': 'డాక్స్ చూడండి',
    'Interactive Agricultural Map': 'ఇంటరాక్టివ్ వ్యవసాయ మ్యాప్',
    'Map Controls & Filters': 'మ్యాప్ నియంత్రణలు మరియు ఫిల్టర్లు',
    'Region': 'ప్రాంతం', 'Crop Type': 'పంట రకం', 'Data Layer': 'డేటా లేయర్',
    'Time Period': 'సమయ వ్యవధి', 'Apply Filters': 'ఫిల్టర్లను వర్తింపజేయండి',
    'Reset Filters': 'ఫిల్టర్లను రీసెట్ చేయండి',
    'Global View': 'గ్లోబల్ వ్యూ', 'North America': 'ఉత్తర అమెరికా',
    'South America': 'దక్షిణ అమెరికా', 'Europe': 'యూరప్', 'Asia': 'ఆసియా',
    'Africa': 'ఆఫ్రికా', 'Oceania': 'ఓషియానియా',
    'All Crops': 'అన్ని పంటలు', 'Satellite View': 'సాటిలైట్ వ్యూ',
    'Weather Data': 'వాతావరణ డేటా', 'Soil Health': 'మట్టి ఆరోగ్యం',
    'Yield Predictions': 'దిగుబడి అంచనాలు', 'Historical Data': 'చారిత్రక డేటా',
    'Terrain': 'భూభాగం', 'Current': 'ప్రస్తుత',
    'Last 7 Days': 'చివరి 7 రోజులు', 'Last 30 Days': 'చివరి 30 రోజులు',
    'Last Season': 'చివరి సీజన్', 'Last Year': 'చివరి సంవత్సరం',
    'Last 5 Years': 'చివరి 5 సంవత్సరాలు',
    'Sign In': 'సైన్ ఇన్', 'Create Account': 'ఖాతా సృష్టించండి',
    'Full Name': 'పూర్తి పేరు', 'Username': 'వినియోగదారు పేరు',
    'Email (Optional)': 'ఇమెయిల్ (ఐచ్ఛికం)', 'Password': 'పాస్‌వర్డ్',
    'Confirm Password': 'పాస్‌వర్డ్ నిర్ధారించండి',
    "Don't have an account?": 'ఖాతా లేదా?',
    'Already have an account?': 'ఇప్పటికే ఖాతా ఉందా?',
    'Sign up here': 'ఇక్కడ సైన్ అప్ చేయండి',
    'Sign in here': 'ఇక్కడ సైన్ ఇన్ చేయండి',
    'By signing up, you agree to our Terms of Service': 'సైన్ అప్ చేయడం ద్వారా, మీరు మా సేవా నిబంధనలకు అంగీకరిస్తున్నారు'
};

maps['te'] = teMap;

let fileContent = fs.readFileSync('translations.js', 'utf8');

const regex = /_getHardcodedTextMap\(lang\) \{[\s\S]*?return maps\[lang\] \|\| null;\s*\}/;

const newMethod = `_getHardcodedTextMap(lang) {
        const maps = ${JSON.stringify(maps, null, 12)};
        
        return maps[lang] || null;
    }`;

fileContent = fileContent.replace(regex, newMethod);

fs.writeFileSync('translations.js', fileContent);
console.log("Successfully injected translations!");
